drop table if exists person;
drop table if exists vacancy;

create table person
(
    id       integer generated by default as identity,
    name     varchar(255) not null,
    password varchar(255) not null,
    age int not null,
    phone_number int not null,
    email varchar(255) not null,
    primary key (id)
);

create table vacancy
(
    id       integer generated by default as identity,
    name     varchar(255) not null,
    description varchar(255) not null,
    primary key (id)
);

create table resume_table
(
    id       integer generated by default as identity,
    description varchar(255) not null,
    primary key (id)
);


insert into vacancy (name, description)
values ('junior java', 'development'), ('middle', 'development'), ('senior', 'development');